name: covt
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.45=bootstrap_ha15bf96_3
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.0=hee844dc_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=h3c07f61_2_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_ha0e22de_103
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - accelerate==1.3.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - altair==5.5.0
      - annotated-doc==0.0.4
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - appdirs==1.4.4
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - av==16.0.1
      - bitsandbytes==0.43.1
      - brotli==1.0.9
      - cachetools==6.2.2
      - certifi==2024.2.2
      - charset-normalizer==2.0.4
      - click==8.1.7
      - comm==0.2.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==2.19.2
      - debugpy==1.6.7
      - decorator==5.1.1
      - decord==0.6.0
      - deepspeed==0.16.4
      - diffusers==0.29.0
      - dill==0.3.8
      - distro==1.9.0
      - dnspython==2.7.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - dotenv==0.9.9
      - einops==0.7.0
      - entrypoints==0.4
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastapi==0.121.3
      - ffmpy==1.0.0
      - filelock==3.13.1
      - flash-attn==2.8.3
      - fonttools==4.60.1
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - ftfy==6.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gmpy2==2.1.2
      - google-auth==2.43.0
      - google-genai==1.52.0
      - gradio==4.29.0
      - gradio-client==0.16.1
      - gradio-imageslider==0.0.20
      - groovy==0.1.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.27.1
      - idna==3.4
      - imageio==2.37.2
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - intel-openmp==2024.1.0
      - ipdb==0.13.13
      - ipykernel==6.29.3
      - ipython==8.22.2
      - ipywidgets==8.1.5
      - jedi==0.19.1
      - jinja2==3.1.3
      - jiter==0.12.0
      - joblib==1.5.2
      - json-repair==0.54.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==7.3.4
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.9
      - liger-kernel==0.5.5
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mkl==2024.1.0
      - mkl-fft==1.3.8
      - mkl-random==1.2.4
      - mkl-service==2.4.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - narwhals==2.12.0
      - nest-asyncio==1.6.0
      - networkx==3.1
      - ninja==1.11.1.1
      - nltk==3.9.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==12.560.30
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - openai==2.8.1
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - orjson==3.11.4
      - packaging==24.0
      - pandas==2.2.2
      - parso==0.8.4
      - peft==0.10.0
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - platformdirs==4.2.0
      - portalocker==3.2.0
      - prompt-toolkit==3.0.42
      - propcache==0.4.1
      - protobuf==4.25.3
      - psutil==5.9.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pydub==0.25.1
      - pygments==2.17.2
      - pynvml==11.5.0
      - pyparsing==3.2.5
      - pysocks==1.7.1
      - python-dateutil==2.9.0
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - qwen-vl-utils==0.0.14
      - referencing==0.37.0
      - regex==2023.12.25
      - requests==2.32.3
      - rich==13.7.1
      - rpds-py==0.29.0
      - rsa==4.9.1
      - ruff==0.14.6
      - safehttpx==0.1.7
      - safetensors==0.4.5
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - segment-anything==1.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==1.45.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - shtab==1.7.1
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - stack-data==0.6.2
      - starlette==0.50.0
      - sty==1.0.6
      - sympy==1.13.1
      - tabulate==0.9.0
      - tbb==2021.12.0
      - tenacity==9.1.2
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - timeout-decorator==0.5.0
      - timm==1.0.22
      - tokenizers==0.21.0
      - tomli==2.3.0
      - tomlkit==0.12.0
      - torch==2.5.1
      - torchao==0.6.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tornado==6.1
      - tqdm==4.66.4
      - traitlets==5.14.2
      - transformers==4.50.1
      - triton==3.1.0
      - trl==0.8.6
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tyro==0.8.4
      - tzdata==2024.1
      - ujson==5.10.0
      - urllib3==2.1.0
      - uvicorn==0.38.0
      - validators==0.35.0
      - vlmeval==0.1.0
      - wandb==0.16.6
      - wcwidth==0.2.13
      - websockets==11.0.3
      - widgetsnbextension==4.0.13
      - xlsxwriter==3.2.9
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.23.0
prefix: /home/yimingqin/anaconda3/envs/covt
