wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.19
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.50.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1763884817.0
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 83
      - 98
      - 105
      3:
      - 13
      - 23
      4: 3.10.19
      5: 0.16.6
      6: 4.50.1
      8:
      - 5
      13: linux-x86_64
